package tutoring.entity;
// Generated Feb 28, 2013 12:05:50 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Integer id;
     private String myuser;
     private String email;
     private String webpage;
     private Date datum;
     private String summery;
     private String comments;

    public Comments() {
    }

	
    public Comments(String myuser, String webpage, Date datum, String summery, String comments) {
        this.myuser = myuser;
        this.webpage = webpage;
        this.datum = datum;
        this.summery = summery;
        this.comments = comments;
    }
    public Comments(String myuser, String email, String webpage, Date datum, String summery, String comments) {
       this.myuser = myuser;
       this.email = email;
       this.webpage = webpage;
       this.datum = datum;
       this.summery = summery;
       this.comments = comments;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMyuser() {
        return this.myuser;
    }
    
    public void setMyuser(String myuser) {
        this.myuser = myuser;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getWebpage() {
        return this.webpage;
    }
    
    public void setWebpage(String webpage) {
        this.webpage = webpage;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public String getSummery() {
        return this.summery;
    }
    
    public void setSummery(String summery) {
        this.summery = summery;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


